### ISSUE TITLE
每隔一会就莫名其妙有被击退的效果

### ISSUE THREAD

**Issue by CacPixel** [SchoolUniform/RealSurvival#11]
```
status-command-cooldown: 600

on-death:
  enable: false
  remove-all-disease: true
  sleep: 80
  thirst: 80
  energy: 80
  hunger: 60

#属性设置,
#sleep  精力
#thirst 水分
#energy 体力
#weight 负重
#共同项如下
#enable 		是否启用
#max 			属性最大值
#sub			每秒减少值
#add			每秒增加值
#effect-data 	效果
#对effect-data讲解
#格式如下
#effect-data:
#  - "[对应属性百分比1*100]-[对应属性百分比2*100]:效果1;效果2;效果n"
#  - "[对应属性百分比3*100]-[对应属性百分比4*100]:null"
#效果可以是原版效果,也可以是另外添加的效果
#效果格式如下:
#效果名,持续时间,效果强度，发生几率(1-100)
#效果名大小写敏感,支持原版效果名
#冒号后面的null代表不产生效果
#对应请在messages.yml中修改提示消息,参考默认配置进行配置
#weight下的effect与effect-data的冒号后边格式一样
status:
  sleep:
    enable: true
    #在白天是否能睡觉
    sleep-in-day: true
    #当属性值到0时是否强制睡觉(当sleep-in-day启用时生效
    sleep-zero: true
    max: 100
    sub: 0.02
    add: 1
    effect-data:
      - "10-0:SPEED,400,-2,65;HEAL,1,5,65"
      - "90-100:SPEED,400,-2,65;HEAL,1,5,65"
  thirst:
    enable: true
    max: 100
    sub: 0.04
    effect-data:
      - "10-0:SPEED,400,-2,65;HEAL,1,-5,65"
      - "80-100:SPEED,400,-2,65;HEAL,1,-5,65"
      #设定生物群系下获取的水
   # - "生物群系名:item文件夹下的文件名(不包括.yml)"
    water:
      - "BIOME:WATER1"
    purifier:
      - "WATER1,WATER2,1"
  energy:
    enable: true
    max: 100
    add: 5
    #潜行消耗体力,0取消,下同
    sneaking: 1
    #奔跑
    sprinting: 3
    #跳跃
    jumping: 3
    #游泳
    swimming: 1
    effect-data:
      - "10-0:SPEED,400,-2,65;HEAL,1,5,65"
    break-block:
      - "SAND,AIR,1"
      #工具列表
    tool-list:
      - "IRON_PICKAXE"
  weight:
    enable: true
    max: 100
    effect: "SPEED,400,-2,65"
  disease:
    enable: true
    mob: true
    disease:
      - "生病:SPEED,400,-2,65;HEAL,1,-2,65"
  temperature: 
    enable: true
    #玩家默认最大容忍温度
    max: 30
    #玩家默认最低容忍温度
    min: 20
    #超过最大容忍温度时赋予的效果
    max-effect: "SPEED,400,-2,65"
    #低于最低容忍温度时赋予的效果
    min-effect: "SPEED,400,-2,65"
    #设定Minecraft原版物品的温度(与基础温度值简单加合)
    block:
      - "TORCH:1"

#老规矩,改冒号后面的
#使用带有disease-source的lore的物品攻击他人能使被攻击者致病
label:
  split: ":"
  labels:
    - "sleep:精力"              #精力
    - "thirst:水分"            #水分
    - "weight:质量"            #负重
    - "hunger:饥饿"            #饥饿值
    - "energy:体力"            #体力
    - "health:生命"            #生命值
    - "drug:药物"                #药物
    - "temperature:温度耐受"  #温度
    - "disease-source:疾病源"
    - "purifier:净水器"

#增加机器,格式如下
# - "机器名称,多方块结构名称,机器类型(现在仅可选CRAFT_TABLE与FURNACE),机器GUI的标题"
machine:
  - "machineName,CubeName,CRAFT_TABLE,Title"    

```

这是配置文件
每过一会，或者/rs reload ，玩家就会被莫名其妙被击退向一方。
另外，温度系统到底哪里可以改？为什么温度不是数字而是冷，寻常和热？像那些普通的树林里也是显示冷就很奇怪。。
